### ISSUE TITLE
SSL cert on ipaaudio.click expired

### ISSUE THREAD

**Issue by theY4Kman** [rcoh/ipa-reader#1]
Hey, thank you for this wonderful extension, which I've used more times than I can count.

Just a heads-up: the certificate for https://ipaaudio.click expired in August 2019, and the Chrome extension has been crippled since then.

![image](https://user-images.githubusercontent.com/33840/79032533-4f4c1e00-7b75-11ea-8633-7a61a30a75d6.png)

I can still workaround it by visiting https://ipaaudio.click directly and hitting the "Proceed to ipaaudio.click (unsafe)" link — for any other readers, click Advanced, then this guy:

![image](https://user-images.githubusercontent.com/33840/79032571-a4882f80-7b75-11ea-8538-53e636dd1377.png)

I'd noticed people commenting about the loss of functionality on the Chrome store, and figured I'd try to touch base.

Cheers!

**Comment by rcoh** [comment]
oh wow, thanks for pointing this out! Will get it fixed soon. Didn't realize anyone was actually using this extension!

**Comment by rcoh** [comment]
Fixed, and autorenew is fixed again. Thanks so much for the report, and thanks for using ipareader!

**Comment by theY4Kman** [comment]
Woohoo! Thank you 😊
